export type Property = { slug: string; title: string; category: "Residential" | "Commercial" | "Project"; type: string; location: string; price: string; specs: string; status: string; image: string; featured?: boolean; developer?: string; description?: string };

export const properties: Property[] = [
  { slug: "the-crest-sector-54", title: "The Crest Residences", category: "Residential", type: "Apartment", location: "Sector 54, Gurugram", price: "₹4.25 Cr onwards", specs: "3 & 4 BHK · 2,380–3,120 sq ft", status: "Ready to move", image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85", featured: true, developer: "Signature Developments", description: "A private collection of light-filled residences overlooking the Aravallis." },
  { slug: "palm-estates-sector-65", title: "Palm Estates", category: "Residential", type: "Villa", location: "Sector 65, Gurugram", price: "₹6.90 Cr onwards", specs: "4 & 5 BHK · 4,200–5,600 sq ft", status: "Under construction", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85", featured: true, developer: "Aurelia Homes", description: "Contemporary villas with generous gardens, private decks and club access." },
  { slug: "one-horizon-office", title: "One Horizon Office", category: "Commercial", type: "Office", location: "Golf Course Road, Gurugram", price: "₹220 / sq ft lease", specs: "8,500 sq ft · Grade A · 72 parking", status: "Available now", image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=85", featured: true, developer: "Horizon Business", description: "A future-ready workspace in the city’s most established commercial corridor." },
  { slug: "crown-plaza-retail", title: "Crown Plaza Retail", category: "Commercial", type: "Retail", location: "Sector 57, Gurugram", price: "₹3.10 Cr onwards", specs: "1,050–2,400 sq ft · High street", status: "Pre-leased options", image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=85", developer: "Crown Urban", description: "High-visibility retail designed for brands that want to be found." },
  { slug: "arbour-sector-63", title: "The Arbour", category: "Project", type: "Upcoming project", location: "Sector 63, Gurugram", price: "₹3.85 Cr onwards", specs: "3 & 4 BHK · Possession Dec 2029", status: "Launching soon", image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85", featured: true, developer: "Haven Group", description: "An early opportunity in a low-density address designed around nature and wellbeing." },
  { slug: "axis-sco-noida", title: "Axis SCO Collection", category: "Commercial", type: "SCO", location: "Sector 142, Noida", price: "₹2.45 Cr onwards", specs: "1,200–2,050 sq ft · Freehold", status: "New launch", image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=85", developer: "Axis Land", description: "Flexible business ownership for retail, food, wellness and professional services." },
];
export const areas = [["Golf Course Road", "Gurugram", "₹3.4 Cr – ₹14 Cr", "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80"], ["Golf Course Extension", "Gurugram", "₹2.1 Cr – ₹8.8 Cr", "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=900&q=80"], ["Noida Expressway", "Noida", "₹1.5 Cr – ₹5.2 Cr", "https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=900&q=80"]];
export function findProperty(slug: string) { return properties.find((p) => p.slug === slug) ?? properties[0]; }
